wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.0012231871021368625
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: random
