_wandb:
    value:
        cli_version: 0.25.0
        e:
            3if6c9p0z6mw7byllv9s8uq6m828uhgb:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "2147483648"
                args:
                    - -l
                    - mean_squared_error
                    - -wd
                    - "0"
                    - -w_i
                    - xavier
                    - --dataset
                    - mnist
                    - --epochs
                    - "10"
                    - --batch_size
                    - "64"
                    - --learning_rate
                    - "0.00025948"
                    - --optimizer
                    - rmsprop
                    - --hidden_size
                    - "128"
                    - "64"
                    - --activation
                    - relu
                    - -nhl
                    - "2"
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "99435626496"
                email: santhoshreddywork@gmail.com
                executable: /Users/santhoshreddy/Documents/Semester2/DA6401/Assignment-1/venv/bin/python3
                git:
                    commit: ef09a79ae464255d7b580aacbc8bc0c1ef82f04c
                    remote: https://github.com/s4nth0sh07/DA6401_ASSIGNMENT_1.git
                host: Santhoshs-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.7.4-arm64-arm-64bit-Mach-O
                program: /Users/santhoshreddy/Documents/Semester2/DA6401/Assignment-1/src/train.py
                python: CPython 3.14.3
                root: /Users/santhoshreddy/Documents/Semester2/DA6401/Assignment-1
                startedAt: "2026-03-05T09:07:13.842416Z"
                writerId: 3if6c9p0z6mw7byllv9s8uq6m828uhgb
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 2
                - 5
                - 12
                - 53
            "2":
                - 2
                - 5
                - 12
                - 53
            "3":
                - 2
                - 16
            "4": 3.14.3
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value:
        - 128
        - 64
learning_rate:
    value: 0.00025948
loss:
    value: mean_squared_error
model_save_path:
    value: src/best_model.npy
num_layers:
    value: 2
optimizer:
    value: rmsprop
wandb_project:
    value: ASSIGNMENT-1
weight_decay:
    value: 0
weight_init:
    value: xavier
