wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: '64'
learning_rate:
  value: 0.0402654741671887
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: random
