_wandb:
    value:
        cli_version: 0.25.0
        e:
            euawih3d57al2qqpwdmdqdspli4pm686:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                args:
                    - --activation=sigmoid
                    - --batch_size=64
                    - --dataset=mnist
                    - --epochs=10
                    - --hidden_size=64 64
                    - --learning_rate=0.0005941580923520882
                    - --loss=cross_entropy
                    - --num_layers=2
                    - --optimizer=nag
                    - --wandb_project=ASSIGNMENT-1
                    - --weight_decay=0
                    - --weight_init=xavier
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "102805712896"
                email: santhoshreddywork@gmail.com
                executable: /Users/santhoshreddy/Documents/Semester2/DA6401/Assignment-1/venv/bin/python3
                git:
                    commit: ef09a79ae464255d7b580aacbc8bc0c1ef82f04c
                    remote: https://github.com/s4nth0sh07/DA6401_ASSIGNMENT_1.git
                host: Santhoshs-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-15.7.4-arm64-arm-64bit-Mach-O
                program: /Users/santhoshreddy/Documents/Semester2/DA6401/Assignment-1/src/train.py
                python: CPython 3.14.3
                root: /Users/santhoshreddy/Documents/Semester2/DA6401/Assignment-1
                startedAt: "2026-03-05T10:41:22.767897Z"
                writerId: euawih3d57al2qqpwdmdqdspli4pm686
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 2
                - 5
                - 12
                - 53
            "2":
                - 2
                - 5
                - 12
                - 53
            "3":
                - 2
                - 14
                - 16
            "4": 3.14.3
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
activation:
    value: sigmoid
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value: 64 64
learning_rate:
    value: 0.0005941580923520882
loss:
    value: cross_entropy
model_save_path:
    value: src/best_model.npy
num_layers:
    value: 2
optimizer:
    value: nag
wandb_project:
    value: ASSIGNMENT-1
weight_decay:
    value: 0
weight_init:
    value: xavier
