wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 128 64
learning_rate:
  value: 0.0018668514883857404
num_layers:
  value: 2
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
