wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.00016826881904843322
num_layers:
  value: 3
optimizer:
  value: momentum
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: xavier
