wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: '64'
learning_rate:
  value: 0.00046734361593782337
num_layers:
  value: 2
optimizer:
  value: sgd
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: random
