wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.0043946303254239665
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
