wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.00022700335008423751
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
