wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.000418960694804215
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
