wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: '128'
learning_rate:
  value: 0.00044285672060398576
loss:
  value: mean_squared_error
num_layers:
  value: 1
optimizer:
  value: nag
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
