wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.0026855184506257446
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: random
