wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: 64 64
learning_rate:
  value: 0.00017661197610389557
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
