wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: '64'
learning_rate:
  value: 0.001705684642125808
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: momentum
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.0005
weight_init:
  value: random
