wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.0021436205534578557
loss:
  value: mean_squared_error
num_layers:
  value: 1
optimizer:
  value: nag
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
