wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.002262798080818162
loss:
  value: mean_squared_error
num_layers:
  value: 2
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
