wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 128 64 32
learning_rate:
  value: 0.015099943472586872
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: momentum
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
