wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 64 64
learning_rate:
  value: 0.00014438049961424963
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0
weight_init:
  value: xavier
