wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: '64'
learning_rate:
  value: 0.01662262622757986
num_layers:
  value: 1
optimizer:
  value: nag
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
