wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_size:
  value: '64'
learning_rate:
  value: 0.08598604422694568
num_layers:
  value: 2
optimizer:
  value: momentum
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: xavier
