wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value: 64 64
learning_rate:
  value: 0.015344995764287809
num_layers:
  value: 3
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: xavier
