wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: '64'
learning_rate:
  value: 0.0420976511629958
num_layers:
  value: 1
optimizer:
  value: momentum
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: xavier
