wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 5
hidden_size:
  value: 128 64
learning_rate:
  value: 0.0017118046371631006
num_layers:
  value: 3
optimizer:
  value: nag
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.005
weight_init:
  value: random
