wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_size:
  value:
  - 64
learning_rate:
  value: 0.012217862932351008
num_layers:
  value: 2
optimizer:
  value: rmsprop
wandb_project:
  value: ASSIGNMENT-1
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
